#!/usr/bin/perl
my $top=`pwd`; chomp $top;

sub scan($) {
	my $old = `pwd`; chomp $old;
	my $cur = shift @_;
	my @x;

	print "scanning $cur\n";
	chdir($cur) || die;

	opendir(X,".") || return;
	while (my $name = readdir(X)) {
		next unless -f $name;
		my $n = lc($name);
		next if $n eq $name;
		print "$name\n";
		rename($name,$n) || die;
	}
	closedir(X);

	opendir(X,".") || return;
	while (my $name = readdir(X)) {
		next if $name =~ m/^\.+$/;
		next if $name eq ".svn";
		next if $name eq ".SVN";
		next unless -d $name;
		my $n = lc($name);
		next if $n eq $name;
		print "$name\n";
		rename($name,$n) || die;
	}
	closedir(X);

	opendir(X,".") || return;
	while (my $name = readdir(X)) {
		next if $name =~ m/^\.+$/;
		next if $name eq ".svn";
		next if $name eq ".SVN";
		next unless -d $name;
		push(@x,$name);
	}
	closedir(X);
	foreach my $name (@x) {
		scan("$cur/$name");
	}

	chdir($old) || die;
}

scan($top);
